# Generated by Django 5.1.5 on 2025-01-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_namber', models.IntegerField(verbose_name='Номер стола')),
                ('items', models.JSONField(verbose_name='Заказанные блюда')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Общая стоимость')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('ready', 'Готово'), ('paid', 'Оплачено')], default='pending', max_length=10, verbose_name='Создан')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
        ),
    ]
