# Generated by Django 5.1.5 on 2025-01-30 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='table_namber',
            new_name='table_number',
        ),
    ]
